baseURL: https://spacedot.xyz/
languageCode: en-us
title: SpaceDot
theme: PaperMod

permalinks:
  posts: /archives/:slug  

enableInlineShortcodes: true
enablePermalinks: true
enableEmoji: true
enableRobotsTXT: true

buildDrafts: true
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  author: Kenshin2438

  # defaultTheme: light
  # defaultTheme: dark
  defaultTheme: auto # to switch between dark or light according to browser theme
  disableThemeToggle: false

  ShowAllPagesInArchive: true
  ShowCodeCopyButtons: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowReadingTime: true
  ShowFullTextinRSS: true
  ShowBreadCrumbs: true
  ShowLastMod: false
  ShowToc: true
  TocOpen: false

  math: true
  comments: true

  profileMode:
    enabled: true
    title: "Kenshin2438" # optional default will be site title
    subtitle: "ACM/Math/Blog/Notes"
    imageUrl: /images/avatar.jpg # optional
    imageTitle: "avatar.jpg" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Notes
        url: "/note/book"
      - name: Posts
        url: "/posts/"
      - name: Blog-old
        url: "https://kenshin2438.top/"
  
  # home-info mode
  # homeInfoParams:
  #   Title: "Hi there \U0001F44B"
  #   Content: Welcome to my blog

  socialIcons: # optional
    - name: github
      url: "https://github.com/Kenshin2438"
    # - name: telegram
    #   url: "https://telegram.org/"
    # - name: qq
    #   url: "https://qq.com/"
    - name: rss
      url: "index.xml"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  
  assets:
    disableHLJS: true

  twikoo:
    version: 1.4.18

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true # HUGO 默认转义 Markdown 文件中的 HTML 代码，如需开启的话

  highlight:
    codeFences: true
    lineNos: true
    # anchorLineNos: false
    guessSyntax: true
    noClasses: true
    style: dracula

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 20
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 30
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 40
    - identifier: links
      name: Links
      url: /links/
      weight: 50