baseURL: https://kenshin2438.top/
languageCode: en-us
title: Kenshin2438
theme: PaperMod

permalinks:
  posts: /archives/:slug.html

enableInlineShortcodes: true
enablePermalinks: true
enableEmoji: true
enableRobotsTXT: true

buildDrafts: true
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  author: Kenshin2438

  # defaultTheme: light
  # defaultTheme: dark
  defaultTheme: auto # to switch between dark or light according to browser theme
  disableThemeToggle: false

  ShowAllPagesInArchive: true
  ShowCodeCopyButtons: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowReadingTime: true
  ShowFullTextinRSS: true
  ShowBreadCrumbs: true
  ShowLastMod: false
  ShowToc: true
  TocOpen: false

  math: true
  comments: true

  profileMode:
    enabled: true
    title: "Kenshin2438's Blog" # optional default will be site title
    subtitle: "ACM/Mathematics/Notes</br>deadline是第一生产力"
    imageUrl: /images/avatar.webp # optional
    imageTitle: "avatar.webp" # optional
    # imageWidth: 120 # custom size
    # imageHeight: 120 # custom size
    buttons:
      # - name: Notes
      #   url: "https://spacedot.xyz/"
      - name: Posts
        url: "/posts/"
      - name: old.Blog
        url: "https://old.kenshin2438.top/"
  
  # home-info mode
  # homeInfoParams:
  #   Title: "Hi there \U0001F44B"
  #   Content: Welcome to my blog

  socialIcons: # optional
    - name: github
      url: "https://github.com/Kenshin2438"
    # - name: telegram
    #   url: "https://telegram.org/"
    # - name: qq
    #   url: "https://qq.com/"
    - name: rss
      url: "index.xml"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  
  assets:
    disableHLJS: false
    # disableFingerprinting: true
    favicon: "/favicon/favicon.ico"
    favicon16x16: "/favicon/favicon-16x16.png"
    favicon32x32: "/favicon/favicon-32x32.png"
    apple_touch_icon: "/favicon/apple-touch-icon.png"
    # safari_pinned_tab: ""

  twikoo:
    version: 1.5.4

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true # HUGO 默认转义 Markdown 文件中的 HTML 代码，如需开启的话

  highlight:
    codeFences: true
    lineNos: true
    anchorLineNos: false
    guessSyntax: true
    noClasses: false
    # style: "" # only for chroma

menu:
  main:
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: links
      name: Links
      url: /links/
      weight: 40
    - identifier: search
      name: Search
      url: /search/
      weight: 50