baseURL: https://spacedot.xyz/
languageCode: en-us
title: SpaceDot
theme: PaperMod

permalinks:
  posts: /archives/:slug  

enableInlineShortcodes: true
enablePermalinks: true
enableEmoji: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  # defaultTheme: light
  # defaultTheme: dark
  defaultTheme: auto # to switch between dark or light according to browser theme
  disableThemeToggle: false

  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  ShowPostNavLinks: true
  ShowShareButtons: false
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowToc: true
  TocOpen: false
  math: true
  comments: true
  hidemeta: false
  hideSummary: false
  ShowFullTextinRSS: true
  ShowAllPagesInArchive: true

  profileMode:
    enabled: true
    title: "Kenshin2438" # optional default will be site title
    subtitle: "ACM/Math/Blog/Notes"
    imageUrl: "images/avatar.jpg" # optional
    imageTitle: "avatar.jpg" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Notes
        url: "/note/"
      - name: Blog-old
        url: "https://kenshin2438.top/"
  
  # home-info mode
  # homeInfoParams:
  #   Title: "Hi there \U0001F44B"
  #   Content: Welcome to my blog

  socialIcons: # optional
    - name: github
      url: "https://github.com/Kenshin2438"
    - name: telegram
      url: "https://telegram.org/"
    - name: qq
      url: "https://qq.com/"
    - name: rss
      url: "index.xml"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
  
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

menu:
  main:
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40